package com.umg.sgau.notificacion.service;
import com.umg.sgau.notificacion.entity.*; import com.umg.sgau.notificacion.repository.*; import com.umg.sgau.usuario.repository.UsuarioRepository; import java.time.*; import java.util.*; import org.springframework.transaction.event.TransactionalEventListener; import org.springframework.transaction.event.TransactionPhase; import org.springframework.data.domain.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*;
@Service public class NotificacionService {
 private final NotificacionRepository notices; private final DispositivoPushRepository devices; private final UsuarioRepository users; private final org.springframework.beans.factory.ObjectProvider<FcmSender> sender;
 public NotificacionService(NotificacionRepository n,DispositivoPushRepository d,UsuarioRepository u,org.springframework.beans.factory.ObjectProvider<FcmSender>s){notices=n;devices=d;users=u;sender=s;}
 @TransactionalEventListener(phase=TransactionPhase.BEFORE_COMMIT) public void guardarEvento(EventoNotificacion e){if(e.usuarioId()!=null)crear(e.usuarioId(),e);if(e.administradores())users.findAll().stream().filter(u->Boolean.TRUE.equals(u.getActivo())&&u.getRoles().stream().anyMatch(r->"ADMIN".equalsIgnoreCase(r.getNombre())&&r.getPermisos().stream().anyMatch(p->"COLEGIATURAS_REGISTRAR_PAGO".equals(p.getCodigo())))).map(u->u.getId()).distinct().forEach(id->crear(id,e));}
 private void crear(Long uid,EventoNotificacion e){if(!notices.existsByUsuarioIdAndEventKey(uid,e.eventKey()))notices.save(Notificacion.builder().usuarioId(uid).eventKey(e.eventKey()).tipo(e.tipo()).titulo(e.titulo()).mensaje(e.mensaje()).destinoTipo(e.destinoTipo()).destinoId(e.destinoId()).build());}
 @Transactional(readOnly=true) public Page<Notificacion> list(Long uid,Pageable p){return notices.findByUsuarioIdOrderByFechaCreacionDesc(uid,p);} @Transactional(readOnly=true)public long unread(Long uid){return notices.countByUsuarioIdAndLeidaFalse(uid);}
 @Transactional public Notificacion get(Long uid,Long id){return notices.findByIdAndUsuarioId(id,uid).orElseThrow(()->new NoSuchElementException("Notificación no disponible."));} @Transactional public Notificacion read(Long uid,Long id){var n=get(uid,id);n.setLeida(true);return n;} @Transactional public int readAll(Long uid){return notices.readAll(uid);} @Transactional public void delete(Long uid,Long id){notices.delete(get(uid,id));} @Transactional public int clear(Long uid){return notices.deleteByUsuarioId(uid);}
 @Transactional public void registerDevice(Long uid,String token){var d=devices.findByToken(token).orElseGet(DispositivoPush::new);d.setToken(token);d.setUsuarioId(uid);devices.save(d);notices.requeueForUser(uid,LocalDateTime.now());} @Transactional public void removeDevice(Long uid,String token){devices.deleteByUsuarioIdAndToken(uid,token);}
 @Scheduled(fixedDelayString="${notifications.outbox-delay-ms:5000}") @Transactional public void dispatch(){FcmSender push=sender.getIfAvailable();if(push==null)return;for(Notificacion n:notices.due(LocalDateTime.now(),PageRequest.of(0,100))){var targets=devices.findByUsuarioId(n.getUsuarioId());if(targets.isEmpty()){n.setEntregaEstado("SIN_DISPOSITIVO");continue;}boolean failed=false;for(DispositivoPush d:targets){try{push.send(d.getToken(),Map.of("notificationId",n.getId().toString(),"type",n.getTipo(),"destinationType",Objects.toString(n.getDestinoTipo(),""),"destinationId",Objects.toString(n.getDestinoId(),"")));}catch(com.google.firebase.messaging.FirebaseMessagingException ex){if(ex.getMessagingErrorCode()==com.google.firebase.messaging.MessagingErrorCode.UNREGISTERED)devices.delete(d);else failed=true;}catch(Exception ex){failed=true;}}n.setIntentos(n.getIntentos()+1);if(failed){n.setEntregaEstado("ERROR");n.setEntregaError("Fallo temporal FCM");n.setNextAttemptAt(LocalDateTime.now().plusMinutes(Math.min(60,1L<<Math.min(6,n.getIntentos()))));}else{n.setEntregaEstado("ENVIADO");n.setEntregaError(null);}}}
}
